name: Lint and Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.1'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run Build
      run: go build .

        - name: Run Test
          run: go test -v ./...

        - name: Run Vet & Lint
          run: |
            go vet .
            golint -set_exit_status=1 .

        - name: Run Coverage
          run: go test -coverprofile=coverage.txt -covermode=atomic ./...

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
